### ISSUE TITLE
removed in HA Core 2025.1

### ISSUE THREAD

**Issue by maxhome75** [erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM#3]
Hello,

Is-it normal?
![cee16d56eef4cfc58cb7a486a97f8fffee2f0860_2_1035x477](https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/assets/131256148/d54379ab-5bd5-4f69-a97d-ebc7a888c0a6)
![26a66f6cd0f7db7e4f507cb4809d1825bf6d7ae4](https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/assets/131256148/10b5738d-579a-4185-b68c-a523865e6207)

message:
Entity fan.rpi_cooling_fan (<class 'custom_components.rpi_fan_gpio_pwm.fan.PwmSimpleFan'>) is using deprecated supported features values which will be removed in HA Core 2025.1

Thanks Frosh

**Comment by erdnaxela02** [comment]
This is normally corrected with these latest updates. https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/commit/8284128bc92b34f2a09b0660d4f131da2a82caa7 / https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/commit/6ad21a24ab0147c96d5fb96fb2105ded408b38a7 / https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/commit/9561f41b45bea85058a3b78e846c5ae3c37f2c34 / https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/commit/d8ca261407e0cfaa6906fcce82fae23230187547 / https://github.com/erdnaxela02/HA-RaspberryPi-FAN-GPIO-PWM/commit/53f86678a399d7bc4d7b5bb3762b7b58c862df9d
For my part I no longer have these warnings.
THANKS !

**Comment by maxhome75** [comment]
it's ok, thanks
